#!/bin/bash
set -e

rm -f out.policy cmds.json poses.json vels.json lane_config.json autogenerated.pomdpx

cd ../ros-lanechanging/autocar/scripts/
rm -f poses.json vels.json cmds.json
python generate_poses.py
cd ../../../sarsop/
cp ../ros-lanechanging/autocar/scripts/poses.json .
cp ../ros-lanechanging/autocar/scripts/vels.json .
cp ../ros-lanechanging/autocar/scripts/lane_config.json .
python make_pomdpx.py
cd solver/src/
./pomdpsol -o ../../out.policy ../../autogenerated.pomdpx
cd ../../
python simulate_policy.py out.policy
cp cmds.json ../ros-lanechanging/autocar/scripts/
